entryPoints:
  web:
    address: ":80"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "tcp://docker-proxy:2375"
    exposedByDefault: false
  file:
    directory: /dynamic
    watch: true

experimental:
  plugins:
    jwt:
      moduleName: "github.com/traefik-plugins/traefik-jwt-plugin"
      version: "v0.7.1"

log:
  level: INFO
